name = "telegram-bot-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "USER_TOPICS", id = "641af48c917c47cb978ecee46d841879" },
  { binding = "USER_BLOCKS", id = "641af48c917c47cb978ecee46d841879" }
]

[vars]
# 这些变量会在部署时从环境变量中读取
ENV_BOT_TOKEN = "${ENV_BOT_TOKEN}"
ENV_BOT_SECRET = "${ENV_BOT_SECRET}"
ENV_ADMIN_UID = "${ENV_ADMIN_UID}"
ENV_GROUP_ID = "${ENV_GROUP_ID}"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true




