name = "telegram-bot-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "USER_TOPICS", id = "YOUR_KV_ID_1" },
  { binding = "USER_BLOCKS", id = "YOUR_KV_ID_2" }
]

[vars]
# 这些变量会在部署时从环境变量中读取
# BOT_TOKEN = ""
# BOT_SECRET = ""
# ADMIN_UID = ""
# GROUP_ID = "" 